services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: rag-confluence-db
    environment:
      POSTGRES_DB: confluence_embeddings
      POSTGRES_USER: ${DB_USERNAME:-confluence_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-confluence_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-confluence_user} -d confluence_embeddings"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: rag-confluence-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local
